version: "3.8"
services:
#  tailscale: # ToDo: Remove in git
#    build:
#      context: ./docker/tailscale-docker/images/tailscale
#    environment:
#      TAILSCALE_AUTH_KEY: ${TAILSCALE_AUTH_KEY:?err}
#      TAILSCALE_HOSTNAME: ${TAILSCALE_HOSTNAME:-tailscale-docker-simple-example}
#      TAILSCALE_STATE_ARG: "mem:"
      # (optional) set additional flags on tailscaled
      # TAILSCALE_OPT: --outbound-http-proxy-listen=localhost:1055
  birdmot-gpu:
    image: jokober/birdmot-gpu:latest
    environment:
      - BirdMOT_DATA_PATH=/opt/local_data

    shm_size: '18gb'
    build:
      context: .

      dockerfile: ./docker/Dockerfile.gpu
    volumes:
        - ./:/opt/BirdMOT
        - /shared/datasets/BirdMOT/:/opt/local_data

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["0"]
              capabilities: [gpu]
    #entrypoint: ["/bin/bash"]
    command: tail -f /dev/null
#    network_mode: "service:tailscale"